/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicBoardRouteImport } from './routes/public/board'
import { Route as ProtectedTeamRouteImport } from './routes/_protected/team'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedIssuesRouteImport } from './routes/_protected/issues'
import { Route as ProtectedFeedbacksRouteImport } from './routes/_protected/feedbacks'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedCompaniesRouteImport } from './routes/_protected/companies'
import { Route as ProtectedBoardsRouteImport } from './routes/_protected/boards'
import { Route as ProtectedBoardRouteImport } from './routes/_protected/board'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PublicBoardBoardUrlRouteImport } from './routes/public/board/$boardUrl'
import { Route as ProtectedCompaniesCompanyIdRouteImport } from './routes/_protected/companies.$companyId'
import { Route as ProtectedBoardBoardIdRouteImport } from './routes/_protected/board/$boardId'

const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicBoardRoute = PublicBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedTeamRoute = ProtectedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIssuesRoute = ProtectedIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFeedbacksRoute = ProtectedFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCompaniesRoute = ProtectedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBoardsRoute = ProtectedBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBoardRoute = ProtectedBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PublicBoardBoardUrlRoute = PublicBoardBoardUrlRouteImport.update({
  id: '/$boardUrl',
  path: '/$boardUrl',
  getParentRoute: () => PublicBoardRoute,
} as any)
const ProtectedCompaniesCompanyIdRoute =
  ProtectedCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => ProtectedCompaniesRoute,
  } as any)
const ProtectedBoardBoardIdRoute = ProtectedBoardBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => ProtectedBoardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/public': typeof PublicRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/board': typeof ProtectedBoardRouteWithChildren
  '/boards': typeof ProtectedBoardsRoute
  '/companies': typeof ProtectedCompaniesRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/feedbacks': typeof ProtectedFeedbacksRoute
  '/issues': typeof ProtectedIssuesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/team': typeof ProtectedTeamRoute
  '/public/board': typeof PublicBoardRouteWithChildren
  '/board/$boardId': typeof ProtectedBoardBoardIdRoute
  '/companies/$companyId': typeof ProtectedCompaniesCompanyIdRoute
  '/public/board/$boardUrl': typeof PublicBoardBoardUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/public': typeof PublicRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/board': typeof ProtectedBoardRouteWithChildren
  '/boards': typeof ProtectedBoardsRoute
  '/companies': typeof ProtectedCompaniesRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/feedbacks': typeof ProtectedFeedbacksRoute
  '/issues': typeof ProtectedIssuesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/team': typeof ProtectedTeamRoute
  '/public/board': typeof PublicBoardRouteWithChildren
  '/board/$boardId': typeof ProtectedBoardBoardIdRoute
  '/companies/$companyId': typeof ProtectedCompaniesCompanyIdRoute
  '/public/board/$boardUrl': typeof PublicBoardBoardUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/public': typeof PublicRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/board': typeof ProtectedBoardRouteWithChildren
  '/_protected/boards': typeof ProtectedBoardsRoute
  '/_protected/companies': typeof ProtectedCompaniesRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/feedbacks': typeof ProtectedFeedbacksRoute
  '/_protected/issues': typeof ProtectedIssuesRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/team': typeof ProtectedTeamRoute
  '/public/board': typeof PublicBoardRouteWithChildren
  '/_protected/board/$boardId': typeof ProtectedBoardBoardIdRoute
  '/_protected/companies/$companyId': typeof ProtectedCompaniesCompanyIdRoute
  '/public/board/$boardUrl': typeof PublicBoardBoardUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/public'
    | '/login'
    | '/signup'
    | '/board'
    | '/boards'
    | '/companies'
    | '/dashboard'
    | '/feedbacks'
    | '/issues'
    | '/settings'
    | '/team'
    | '/public/board'
    | '/board/$boardId'
    | '/companies/$companyId'
    | '/public/board/$boardUrl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/public'
    | '/login'
    | '/signup'
    | '/board'
    | '/boards'
    | '/companies'
    | '/dashboard'
    | '/feedbacks'
    | '/issues'
    | '/settings'
    | '/team'
    | '/public/board'
    | '/board/$boardId'
    | '/companies/$companyId'
    | '/public/board/$boardUrl'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/public'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_protected/board'
    | '/_protected/boards'
    | '/_protected/companies'
    | '/_protected/dashboard'
    | '/_protected/feedbacks'
    | '/_protected/issues'
    | '/_protected/settings'
    | '/_protected/team'
    | '/public/board'
    | '/_protected/board/$boardId'
    | '/_protected/companies/$companyId'
    | '/public/board/$boardUrl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/board': {
      id: '/public/board'
      path: '/board'
      fullPath: '/public/board'
      preLoaderRoute: typeof PublicBoardRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/team': {
      id: '/_protected/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ProtectedTeamRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/issues': {
      id: '/_protected/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof ProtectedIssuesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/feedbacks': {
      id: '/_protected/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof ProtectedFeedbacksRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/companies': {
      id: '/_protected/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof ProtectedCompaniesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/boards': {
      id: '/_protected/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof ProtectedBoardsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/board': {
      id: '/_protected/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof ProtectedBoardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/public/board/$boardUrl': {
      id: '/public/board/$boardUrl'
      path: '/$boardUrl'
      fullPath: '/public/board/$boardUrl'
      preLoaderRoute: typeof PublicBoardBoardUrlRouteImport
      parentRoute: typeof PublicBoardRoute
    }
    '/_protected/companies/$companyId': {
      id: '/_protected/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof ProtectedCompaniesCompanyIdRouteImport
      parentRoute: typeof ProtectedCompaniesRoute
    }
    '/_protected/board/$boardId': {
      id: '/_protected/board/$boardId'
      path: '/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof ProtectedBoardBoardIdRouteImport
      parentRoute: typeof ProtectedBoardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedBoardRouteChildren {
  ProtectedBoardBoardIdRoute: typeof ProtectedBoardBoardIdRoute
}

const ProtectedBoardRouteChildren: ProtectedBoardRouteChildren = {
  ProtectedBoardBoardIdRoute: ProtectedBoardBoardIdRoute,
}

const ProtectedBoardRouteWithChildren = ProtectedBoardRoute._addFileChildren(
  ProtectedBoardRouteChildren,
)

interface ProtectedCompaniesRouteChildren {
  ProtectedCompaniesCompanyIdRoute: typeof ProtectedCompaniesCompanyIdRoute
}

const ProtectedCompaniesRouteChildren: ProtectedCompaniesRouteChildren = {
  ProtectedCompaniesCompanyIdRoute: ProtectedCompaniesCompanyIdRoute,
}

const ProtectedCompaniesRouteWithChildren =
  ProtectedCompaniesRoute._addFileChildren(ProtectedCompaniesRouteChildren)

interface ProtectedRouteChildren {
  ProtectedBoardRoute: typeof ProtectedBoardRouteWithChildren
  ProtectedBoardsRoute: typeof ProtectedBoardsRoute
  ProtectedCompaniesRoute: typeof ProtectedCompaniesRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedFeedbacksRoute: typeof ProtectedFeedbacksRoute
  ProtectedIssuesRoute: typeof ProtectedIssuesRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTeamRoute: typeof ProtectedTeamRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBoardRoute: ProtectedBoardRouteWithChildren,
  ProtectedBoardsRoute: ProtectedBoardsRoute,
  ProtectedCompaniesRoute: ProtectedCompaniesRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedFeedbacksRoute: ProtectedFeedbacksRoute,
  ProtectedIssuesRoute: ProtectedIssuesRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTeamRoute: ProtectedTeamRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicBoardRouteChildren {
  PublicBoardBoardUrlRoute: typeof PublicBoardBoardUrlRoute
}

const PublicBoardRouteChildren: PublicBoardRouteChildren = {
  PublicBoardBoardUrlRoute: PublicBoardBoardUrlRoute,
}

const PublicBoardRouteWithChildren = PublicBoardRoute._addFileChildren(
  PublicBoardRouteChildren,
)

interface PublicRouteChildren {
  PublicBoardRoute: typeof PublicBoardRouteWithChildren
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBoardRoute: PublicBoardRouteWithChildren,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
